import type { Audit, Finding } from "@/hooks/useAudits";

interface VulnerabilityCounts {
  critical: number;
  high: number;
  medium: number;
  low: number;
  info: number;
}

interface ExportOptions {
  audit: Audit;
  findings: Finding[];
  vulnerabilityCounts: VulnerabilityCounts;
}

export const generateMarkdownReport = (options: ExportOptions): string => {
  const { audit, findings, vulnerabilityCounts } = options;
  const date = new Date(audit.created_at).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const totalFindings = Object.values(vulnerabilityCounts).reduce((a, b) => a + b, 0);

  let markdown = `# 🔒 Security Audit Report

**Powered by Solarizer** | Smart Contract Security Analysis

---

## Executive Summary

| Field | Value |
|-------|-------|
| **Project** | ${audit.project_name} |
| **Date** | ${date} |
| **Security Grade** | ${audit.grade || 'Pending'} |
| **Security Score** | ${audit.security_score ?? '--'}/100 |
| **Contracts Analyzed** | ${audit.contract_count} |
| **Lines of Code** | ${audit.nloc_count?.toLocaleString() ?? 'N/A'} |

---

## Vulnerability Summary

| Severity | Count |
|----------|-------|
| 🔴 Critical | ${vulnerabilityCounts.critical} |
| 🟠 High | ${vulnerabilityCounts.high} |
| 🟡 Medium | ${vulnerabilityCounts.medium} |
| 🔵 Low | ${vulnerabilityCounts.low} |
| ⚪ Info | ${vulnerabilityCounts.info} |
| **Total** | **${totalFindings}** |

---

## Scope

The following contracts were included in this security audit:

- **${audit.contract_count}** contract${audit.contract_count !== 1 ? 's' : ''} analyzed
${audit.nloc_count ? `- **${audit.nloc_count.toLocaleString()}** lines of code reviewed` : ''}

---

## Findings

`;

  // Group findings by severity
  const severityOrder: Array<'critical' | 'high' | 'medium' | 'low' | 'info'> = ['critical', 'high', 'medium', 'low', 'info'];
  const severityEmoji: Record<string, string> = {
    critical: '🔴',
    high: '🟠',
    medium: '🟡',
    low: '🔵',
    info: '⚪'
  };

  severityOrder.forEach(severity => {
    const severityFindings = findings.filter(f => f.severity === severity);
    if (severityFindings.length > 0) {
      markdown += `### ${severityEmoji[severity]} ${severity.charAt(0).toUpperCase() + severity.slice(1)} Severity (${severityFindings.length})\n\n`;
      
      severityFindings.forEach((finding, index) => {
        markdown += `#### ${index + 1}. ${finding.title}\n\n`;
        markdown += `${finding.description}\n\n`;
        
        if (finding.location) {
          const lines = finding.line_start && finding.line_end 
            ? (finding.line_start === finding.line_end 
                ? `L${finding.line_start}` 
                : `L${finding.line_start}-${finding.line_end}`)
            : '';
          markdown += `**Location:** \`${finding.location}${lines ? `:${lines}` : ''}\`\n\n`;
        }
        
        if (finding.code_snippet) {
          markdown += `**Affected Code:**\n\`\`\`solidity\n${finding.code_snippet}\n\`\`\`\n\n`;
        }
        
        if (finding.remediation) {
          markdown += `**Remediation:**\n${finding.remediation}\n\n`;
        }
        
        markdown += `---\n\n`;
      });
    }
  });

  if (findings.length === 0) {
    markdown += `*No security findings were identified in this audit.*\n\n---\n\n`;
  }

  // Footer
  const generatedDate = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric', 
    hour: '2-digit', 
    minute: '2-digit' 
  });

  markdown += `## Disclaimer

This report was generated by Solarizer, an automated smart contract security analysis tool. While we strive for accuracy, this report should not be considered a substitute for a comprehensive manual security audit. Always conduct thorough testing before deploying smart contracts to production.

---

*Report generated on ${generatedDate}*

**© ${new Date().getFullYear()} Solarizer** | [enxpro.lovable.app](https://enxpro.lovable.app)
`;

  return markdown;
};

export const downloadMarkdown = (content: string, filename: string) => {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
