import { Link } from "react-router-dom";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const TermsOfService = () => {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Header />

      <main className="flex-1 container max-w-4xl mx-auto px-4 pt-24 pb-12">
        <div className="mb-8">
          <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
          <p className="text-muted-foreground">Last updated: February 22, 2026</p>
        </div>

        {/* Table of Contents */}
        <div className="bg-card border border-border rounded-lg p-6 mb-8">
          <h2 className="text-lg font-semibold mb-4">Table of Contents</h2>
          <nav className="space-y-2">
            <a href="#definitions" className="block text-primary hover:underline">1. Definitions</a>
            <a href="#acceptance" className="block text-primary hover:underline">2. Acceptance of Terms</a>
            <a href="#eligibility" className="block text-primary hover:underline">3. Eligibility & Account Security</a>
            <a href="#service" className="block text-primary hover:underline">4. Service Description</a>
            <a href="#subscriptions" className="block text-primary hover:underline">5. Subscription Plans & Credits</a>
            <a href="#ip" className="block text-primary hover:underline">6. Intellectual Property</a>
            <a href="#acceptable-use" className="block text-primary hover:underline">7. Acceptable Use Policy</a>
            <a href="#confidentiality" className="block text-primary hover:underline">8. Confidentiality & Data Handling</a>
            <a href="#warranties" className="block text-primary hover:underline">9. Disclaimer of Warranties</a>
            <a href="#liability" className="block text-primary hover:underline">10. Limitation of Liability</a>
            <a href="#indemnification" className="block text-primary hover:underline">11. Indemnification</a>
            <a href="#termination" className="block text-primary hover:underline">12. Termination</a>
            <a href="#modifications" className="block text-primary hover:underline">13. Modifications to Terms</a>
            <a href="#governing-law" className="block text-primary hover:underline">14. Governing Law & Dispute Resolution</a>
            <a href="#general" className="block text-primary hover:underline">15. General Provisions</a>
            <a href="#contact" className="block text-primary hover:underline">16. Contact</a>
          </nav>
        </div>

        {/* Terms Content */}
        <div className="prose prose-invert max-w-none space-y-8">
          {/* Section 1: Definitions */}
          <section id="definitions">
            <h2 className="text-xl font-semibold text-foreground border-b border-border pb-2 mb-4">
              1. Definitions
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              The following definitions apply throughout these Terms of Service:
            </p>
            <div className="bg-muted/30 border border-border rounded-lg p-4 space-y-3">
              <p className="text-muted-foreground text-sm leading-relaxed">
                <strong className="text-foreground">"Service"</strong> means the Solarizer platform, including the Solarizer CLI (command-line interface), the Solarizer web dashboard, all associated APIs, and any related documentation, tools, or features made available by Solarizer.
              </p>
              <p className="text-muted-foreground text-sm leading-relaxed">
                <strong className="text-foreground">"Content"</strong> or <strong className="text-foreground">"Your Content"</strong> means any smart contract source code, files, metadata, or other materials you submit to the Service for analysis.
              </p>
              <p className="text-muted-foreground text-sm leading-relaxed">
                <strong className="text-foreground">"Analysis Output"</strong> means the security findings, vulnerability reports, remediation guidance, and any other output generated by the Service in connection with your Content.
              </p>
              <p className="text-muted-foreground text-sm leading-relaxed">
                <strong className="text-foreground">"Credits"</strong> means the unit of consumption used to measure and pay for analysis performed by the Service. One Credit corresponds to one normalized line of code (nLOC), subject to applicable complexity multipliers and discount rates.
              </p>
              <p className="text-muted-foreground text-sm leading-relaxed">
                <strong className="text-foreground">"Additional Credits"</strong> means additional Credits purchased separately from your subscription allocation.
              </p>
              <p className="text-muted-foreground text-sm leading-relaxed">
                <strong className="text-foreground">"Subscription Plan"</strong> means the tier of service you have selected (Spark, Blaze, or Inferno), each of which provides different feature access, scope limits, and Credit pricing.
              </p>
              <p className="text-muted-foreground text-sm leading-relaxed">
                <strong className="text-foreground">"nLOC"</strong> means normalized lines of code, calculated by excluding blank lines, comments, and import statements from the raw line count of a source file.
              </p>
            </div>
          </section>

          {/* Section 2: Acceptance of Terms */}
          <section id="acceptance">
            <h2 className="text-xl font-semibold text-foreground border-b border-border pb-2 mb-4">
              2. Acceptance of Terms
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              By accessing, installing, or using any part of the Service — including creating an account, running the Solarizer CLI, or accessing the web dashboard — you acknowledge that you have read, understood, and agree to be bound by these Terms of Service ("Terms"). These Terms constitute a legally binding agreement between you (individually, or on behalf of the entity you represent) and Solarizer ("we," "our," or "us"). Solarizer is currently a brand name; the operating entity is in the process of incorporation. These Terms will be updated to reflect the incorporated entity once established.
            </p>
            <p className="text-muted-foreground leading-relaxed mb-4">
              If you are entering into these Terms on behalf of an organization, you represent and warrant that you have the authority to bind that organization to these Terms. If you do not have such authority, or if you do not agree with these Terms, you must not use the Service.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              Your use of the Service is also governed by our{" "}
              <Link to="/privacy" className="text-primary hover:underline">Privacy Policy</Link>, which is incorporated into these Terms by reference.
            </p>
          </section>

          {/* Section 3: Eligibility & Account Security */}
          <section id="eligibility">
            <h2 className="text-xl font-semibold text-foreground border-b border-border pb-2 mb-4">
              3. Eligibility & Account Security
            </h2>
            <div className="space-y-4">
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">3.1 Eligibility</h3>
                <p className="text-muted-foreground leading-relaxed">
                  You must be at least 18 years of age (or the age of legal majority in your jurisdiction) to create an account and use the Service. The Service is not available to users in jurisdictions where its use would be prohibited by applicable law or regulation.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">3.2 Account Registration</h3>
                <p className="text-muted-foreground leading-relaxed">
                  To access certain features of the Service, you must create an account and provide accurate, complete, and current information. You agree to update your account information promptly to keep it accurate.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">3.3 Account Security</h3>
                <p className="text-muted-foreground leading-relaxed">
                  You are solely responsible for maintaining the confidentiality of your account credentials, including your API key. You must not share your account credentials or API key with any third party. You are responsible for all activity that occurs under your account, whether or not authorized by you.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">3.4 Account Sharing</h3>
                <p className="text-muted-foreground leading-relaxed">
                  Each account is licensed for use by a single individual or, for Business-tier accounts, by the authorized members of a single organization. Sharing accounts between unrelated parties, reselling access, or operating a service bureau using Solarizer accounts is prohibited.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">3.5 Notification of Breach</h3>
                <p className="text-muted-foreground leading-relaxed">
                  You agree to notify us immediately at{" "}
                  <a href="mailto:hello@solarizer.io" className="text-primary hover:underline">hello@solarizer.io</a>{" "}
                  if you become aware of any unauthorized use of your account or any other breach of security.
                </p>
              </div>
            </div>
          </section>

          {/* Section 4: Service Description */}
          <section id="service">
            <h2 className="text-xl font-semibold text-foreground border-b border-border pb-2 mb-4">
              4. Service Description
            </h2>
            <div className="space-y-4">
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">4.1 Overview</h3>
                <p className="text-muted-foreground leading-relaxed">
                  Solarizer provides AI-powered smart contract security analysis through a terminal-based command-line interface (CLI) and an accompanying web dashboard. The Service performs automated multi-phase security analysis of Solidity smart contract source code and generates structured vulnerability reports.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">4.2 Analysis Pipeline</h3>
                <p className="text-muted-foreground leading-relaxed">
                  The Service employs a multi-phase analysis pipeline that may include complexity classification, vulnerability scanning, deep analysis, cross-contract interaction analysis, false-positive validation, quality assurance scanning, and report generation. The specific phases available to you depend on your Subscription Plan.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">4.3 Reports</h3>
                <p className="text-muted-foreground leading-relaxed">
                  Analysis Output is provided in structured report format. All plans include a local report generated on your machine. Dashboard report access and sharing capabilities vary by Subscription Plan.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">4.4 Checkpoint & Resume</h3>
                <p className="text-muted-foreground leading-relaxed">
                  The Service supports checkpointing during analysis. If an analysis session is interrupted, you may resume from the last completed phase without re-running prior phases.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">4.5 No Guarantee of Completeness</h3>
                <p className="text-muted-foreground leading-relaxed">
                  The Service is an analytical tool designed to assist in identifying potential security vulnerabilities. It is not a substitute for a comprehensive manual security audit, formal verification, or other professional security review. The Service does not guarantee detection of all vulnerabilities, and the absence of findings does not certify that a smart contract is free of defects or security issues.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">4.6 Availability</h3>
                <p className="text-muted-foreground leading-relaxed">
                  The Service is provided on an "as-is" and "as-available" basis. We do not guarantee uninterrupted, timely, secure, or error-free operation of the Service. We reserve the right to modify, suspend, or discontinue any part of the Service at any time, with or without notice.
                </p>
              </div>
            </div>
          </section>

          {/* Section 5: Subscription Plans & Credits */}
          <section id="subscriptions">
            <h2 className="text-xl font-semibold text-foreground border-b border-border pb-2 mb-4">
              5. Subscription Plans & Credits
            </h2>
            <div className="space-y-4">
              <div className="bg-muted/30 border border-border rounded-lg p-4">
                <h3 className="text-lg font-medium text-foreground mb-2">5.1 Subscription Tiers</h3>
                <p className="text-muted-foreground leading-relaxed mb-3">
                  Solarizer offers the following Subscription Plans:
                </p>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b border-border">
                        <th className="text-left py-2 pr-4 text-foreground font-medium">Plan</th>
                        <th className="text-center py-2 px-4 text-foreground font-medium">Monthly Price</th>
                        <th className="text-center py-2 px-4 text-foreground font-medium">Monthly Credits</th>
                        <th className="text-center py-2 px-4 text-foreground font-medium">Credit Rate</th>
                        <th className="text-center py-2 pl-4 text-foreground font-medium">Max Scope</th>
                      </tr>
                    </thead>
                    <tbody className="text-muted-foreground">
                      <tr className="border-b border-border/50">
                        <td className="py-2 pr-4 font-medium text-foreground">Spark</td>
                        <td className="text-center py-2 px-4">$149/mo</td>
                        <td className="text-center py-2 px-4">50</td>
                        <td className="text-center py-2 px-4">$1.00/credit</td>
                        <td className="text-center py-2 pl-4">500 nLOC</td>
                      </tr>
                      <tr className="border-b border-border/50">
                        <td className="py-2 pr-4 font-medium text-foreground">Blaze</td>
                        <td className="text-center py-2 px-4">$199/mo</td>
                        <td className="text-center py-2 px-4">100</td>
                        <td className="text-center py-2 px-4">$1.00/credit</td>
                        <td className="text-center py-2 pl-4">3,000 nLOC</td>
                      </tr>
                      <tr>
                        <td className="py-2 pr-4 font-medium text-foreground">Inferno</td>
                        <td className="text-center py-2 px-4">$499/mo</td>
                        <td className="text-center py-2 px-4">200</td>
                        <td className="text-center py-2 px-4">$1.00/credit</td>
                        <td className="text-center py-2 pl-4">9,999 nLOC</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <p className="text-muted-foreground text-sm mt-3">
                  Features, analysis depth, and scope limits vary by plan. A detailed comparison is available on our{" "}
                  <Link to="/pricing" className="text-primary hover:underline">Pricing page</Link>.
                </p>
              </div>

              <div className="bg-muted/30 border border-border rounded-lg p-4">
                <h3 className="text-lg font-medium text-foreground mb-2">5.2 Credits</h3>
                <p className="text-muted-foreground leading-relaxed mb-3">
                  Each Subscription Plan includes a monthly allocation of Credits (Spark 50, Blaze 100, Inferno 200). Unused Credits carry forward indefinitely and do not expire as long as you maintain an active subscription. Credits are consumed based on the following formula:
                </p>
                <div className="bg-muted/50 border border-border rounded-lg p-4 my-3">
                  <code className="text-primary font-mono text-sm whitespace-pre-line">
                    {"Audit Cost =\n  Sum of (Scope File nLOC × Complexity Multiplier)\n  + Sum of (Context File nLOC × 0.15)"}
                  </code>
                </div>
                <p className="text-muted-foreground text-sm">
                  Complexity multipliers are: L1 (Standard) = 0.8×, L2 (Complex) = 1.0×, L3 (Novel) = 1.2×. Context files — interfaces, libraries, and dependencies included for analysis context — are charged at a discounted rate of 0.15×.
                </p>
              </div>

              <div className="bg-muted/30 border border-border rounded-lg p-4">
                <h3 className="text-lg font-medium text-foreground mb-2">5.3 Additional Credits</h3>
                <p className="text-muted-foreground leading-relaxed">
                  You may purchase additional Credits at a flat rate of $1.00 per credit, regardless of your Subscription Plan. Additional Credits are added to your balance immediately upon purchase and do not expire as long as you maintain an active subscription.
                </p>
              </div>

              <div className="bg-muted/30 border border-border rounded-lg p-4">
                <h3 className="text-lg font-medium text-foreground mb-2">5.4 Scope Limits</h3>
                <p className="text-muted-foreground leading-relaxed">
                  Each Subscription Plan enforces a maximum audit scope per analysis session, measured in total nLOC across all files (scope and context). If your combined file selection exceeds your plan's limit, the Service will not initiate the analysis until the selection is reduced or your plan is upgraded.
                </p>
              </div>

              <div className="bg-muted/30 border border-border rounded-lg p-4">
                <h3 className="text-lg font-medium text-foreground mb-2">5.5 Credit Conversion on Downgrade</h3>
                <p className="text-muted-foreground leading-relaxed mb-3">
                  Upon downgrading your Subscription Plan, your remaining Credits are preserved. Since all plans share a flat $1.00 per credit rate, no conversion is necessary:
                </p>
                <div className="bg-muted/50 border border-border rounded-lg p-4 my-3">
                  <code className="text-primary font-mono text-sm">
                    New Balance = ⌊(Remaining Credits × Old Plan Rate) / New Plan Rate⌋
                  </code>
                </div>
                <p className="text-muted-foreground text-sm">
                  Upgrades do not trigger credit conversion; your balance remains unchanged.
                </p>
              </div>

              <div className="bg-muted/30 border border-border rounded-lg p-4">
                <h3 className="text-lg font-medium text-foreground mb-2">5.6 Billing & Renewal</h3>
                <p className="text-muted-foreground leading-relaxed">
                  Subscriptions are billed on a monthly recurring basis. Your subscription automatically renews at the end of each billing cycle unless cancelled before the renewal date. Applicable taxes are added based on your location. Payments are processed through our designated third-party payment processors.
                </p>
              </div>

              <div className="bg-muted/30 border border-border rounded-lg p-4">
                <h3 className="text-lg font-medium text-foreground mb-2">5.7 Price Changes</h3>
                <p className="text-muted-foreground leading-relaxed">
                  We reserve the right to change subscription prices or Credit rates upon 30 days' prior notice. Price changes take effect at the start of the next billing cycle following the notice period.
                </p>
              </div>
            </div>
          </section>

          {/* Section 6: Intellectual Property */}
          <section id="ip">
            <h2 className="text-xl font-semibold text-foreground border-b border-border pb-2 mb-4">
              6. Intellectual Property
            </h2>
            <div className="space-y-4">
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">6.1 Your Content</h3>
                <p className="text-muted-foreground leading-relaxed">
                  You retain all ownership rights in Your Content. By submitting Content to the Service, you grant Solarizer a limited, non-exclusive, non-transferable, revocable license to process, analyze, and temporarily store your Content solely for the purpose of providing the Service to you. This license terminates when your Content is deleted or your session ends, whichever occurs first.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">6.2 Analysis Output</h3>
                <p className="text-muted-foreground leading-relaxed">
                  You own the substantive findings and vulnerability information contained in Analysis Output generated from Your Content. Solarizer retains ownership of the report format, structure, templates, scoring methodologies, and presentation elements used to deliver the Analysis Output.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">6.3 Solarizer Intellectual Property</h3>
                <p className="text-muted-foreground leading-relaxed">
                  The Service, including its analysis engine, AI models, detection patterns, algorithms, user interface, branding, and documentation, is owned by Solarizer and protected by intellectual property laws. Nothing in these Terms grants you any right, title, or interest in the Service beyond the limited right to use it in accordance with these Terms.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">6.4 Feedback</h3>
                <p className="text-muted-foreground leading-relaxed">
                  If you provide suggestions, ideas, or other feedback regarding the Service ("Feedback"), you grant Solarizer an unrestricted, irrevocable, perpetual, royalty-free license to use, modify, and incorporate such Feedback into the Service without obligation to you.
                </p>
              </div>
            </div>
          </section>

          {/* Section 7: Acceptable Use Policy */}
          <section id="acceptable-use">
            <h2 className="text-xl font-semibold text-foreground border-b border-border pb-2 mb-4">
              7. Acceptable Use Policy
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              You agree not to, and will not permit any third party to:
            </p>
            <ul className="text-muted-foreground text-sm space-y-2 ml-2">
              <li className="flex items-start gap-2"><span className="text-primary mt-1">•</span><span>Reverse-engineer, decompile, disassemble, or otherwise attempt to discover the source code, algorithms, or underlying architecture of the Service.</span></li>
              <li className="flex items-start gap-2"><span className="text-primary mt-1">•</span><span>Use the Service, its outputs, or any information derived from the Service to develop, train, or improve a competing product or service.</span></li>
              <li className="flex items-start gap-2"><span className="text-primary mt-1">•</span><span>Circumvent, disable, or interfere with any security, rate-limiting, scope-limiting, or access-control features of the Service.</span></li>
              <li className="flex items-start gap-2"><span className="text-primary mt-1">•</span><span>Access or use the Service through automated means (bots, scrapers, or scripts) without prior written authorization.</span></li>
              <li className="flex items-start gap-2"><span className="text-primary mt-1">•</span><span>Submit Content that you do not have the right to analyze, or that violates the intellectual property rights of any third party.</span></li>
              <li className="flex items-start gap-2"><span className="text-primary mt-1">•</span><span>Submit Content designed to exploit, attack, or compromise the integrity of the Service or its infrastructure.</span></li>
              <li className="flex items-start gap-2"><span className="text-primary mt-1">•</span><span>Use the Service to facilitate any illegal activity, including but not limited to money laundering, sanctions evasion, or fraud.</span></li>
              <li className="flex items-start gap-2"><span className="text-primary mt-1">•</span><span>Share, redistribute, or publicly disclose Analysis Output in a manner that misrepresents the scope, accuracy, or completeness of the analysis performed.</span></li>
              <li className="flex items-start gap-2"><span className="text-primary mt-1">•</span><span>Exceed your Subscription Plan's scope or credit limits through technical manipulation or abuse of the checkpoint/resume functionality.</span></li>
              <li className="flex items-start gap-2"><span className="text-primary mt-1">•</span><span>Use the Service in any manner that could damage, disable, overburden, or impair the Service or interfere with any other party's use of the Service.</span></li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mt-4">
              Violation of this Acceptable Use Policy may result in immediate suspension or termination of your account without notice.
            </p>
          </section>

          {/* Section 8: Confidentiality & Data Handling */}
          <section id="confidentiality">
            <h2 className="text-xl font-semibold text-foreground border-b border-border pb-2 mb-4">
              8. Confidentiality & Data Handling
            </h2>
            <div className="space-y-4">
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">8.1 Zero-Retention Processing</h3>
                <p className="text-muted-foreground leading-relaxed">
                  Your Content is processed in isolated, session-scoped environments. Source code submitted for analysis is not retained on our infrastructure beyond the duration of your active analysis session. When the session ends, the processing environment is destroyed.
                </p>
              </div>
              <div className="bg-primary/10 border border-primary/30 rounded-lg p-4">
                <h3 className="text-lg font-medium text-primary mb-2">8.2 No Training on Your Code</h3>
                <p className="text-muted-foreground leading-relaxed">
                  Solarizer does not use Your Content to train, fine-tune, or improve its AI models. Your source code is processed solely for the purpose of generating your Analysis Output.
                </p>
              </div>
              <div className="bg-primary/10 border border-primary/30 rounded-lg p-4">
                <h3 className="text-lg font-medium text-primary mb-2">8.3 Isolated Environments</h3>
                <p className="text-muted-foreground leading-relaxed">
                  Each analysis session runs in its own sandboxed environment with no shared state between sessions or users. This ensures that Your Content is never accessible to other users or commingled with other users' data during processing.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">8.4 Data Handling</h3>
                <p className="text-muted-foreground leading-relaxed">
                  For complete information about how we collect, use, and protect your data, refer to our{" "}
                  <Link to="/privacy" className="text-primary hover:underline">Privacy Policy</Link>.
                </p>
              </div>
            </div>
          </section>

          {/* Section 9: Disclaimer of Warranties */}
          <section id="warranties">
            <h2 className="text-xl font-semibold text-foreground border-b border-border pb-2 mb-4">
              9. Disclaimer of Warranties
            </h2>
            <div className="bg-destructive/10 border border-destructive/30 rounded-lg p-4 mb-4">
              <p className="text-sm font-medium text-destructive mb-2">Critical Disclaimer</p>
              <p className="text-muted-foreground text-sm leading-relaxed mb-3">
                TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE. SOLARIZER SPECIFICALLY DISCLAIMS ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ACCURACY.
              </p>
              <p className="text-muted-foreground text-sm leading-relaxed mb-2">WITHOUT LIMITING THE FOREGOING:</p>
              <ul className="text-muted-foreground text-sm space-y-2 ml-2">
                <li className="flex items-start gap-2"><span className="text-destructive mt-1">•</span><span>Solarizer does not warrant that the Service will detect all vulnerabilities, security defects, or risks in Your Content.</span></li>
                <li className="flex items-start gap-2"><span className="text-destructive mt-1">•</span><span>Solarizer does not warrant that smart contracts analyzed by the Service are safe to deploy, free of exploits, or otherwise secure.</span></li>
                <li className="flex items-start gap-2"><span className="text-destructive mt-1">•</span><span>Solarizer does not warrant that the Analysis Output is complete, accurate, or current.</span></li>
                <li className="flex items-start gap-2"><span className="text-destructive mt-1">•</span><span>The Service is not a substitute for a professional manual security audit, formal verification, or independent security review.</span></li>
                <li className="flex items-start gap-2"><span className="text-destructive mt-1">•</span><span>You acknowledge that deploying smart contracts involves inherent risks, and you assume all responsibility for the security of your deployed code.</span></li>
              </ul>
            </div>
          </section>

          {/* Section 10: Limitation of Liability */}
          <section id="liability">
            <h2 className="text-xl font-semibold text-foreground border-b border-border pb-2 mb-4">
              10. Limitation of Liability
            </h2>
            <div className="bg-destructive/10 border border-destructive/30 rounded-lg p-4 space-y-4">
              <div>
                <h3 className="text-sm font-medium text-destructive mb-2">10.1 Liability Cap</h3>
                <p className="text-muted-foreground text-sm leading-relaxed">
                  TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, SOLARIZER'S TOTAL AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE TOTAL AMOUNT YOU PAID TO SOLARIZER IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM.
                </p>
              </div>
              <div>
                <h3 className="text-sm font-medium text-destructive mb-2">10.2 Exclusion of Damages</h3>
                <p className="text-muted-foreground text-sm leading-relaxed">
                  IN NO EVENT SHALL SOLARIZER BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO: LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF DATA, LOSS OF DIGITAL ASSETS, FINANCIAL LOSSES RESULTING FROM EXPLOITS OR SECURITY BREACHES IN ANALYZED CONTRACTS, BUSINESS INTERRUPTION, OR COST OF SUBSTITUTE SERVICES — WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT SOLARIZER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
                </p>
              </div>
              <div>
                <h3 className="text-sm font-medium text-destructive mb-2">10.3 Basis of the Bargain</h3>
                <p className="text-muted-foreground text-sm leading-relaxed">
                  THE LIMITATIONS AND EXCLUSIONS IN THIS SECTION REFLECT A FAIR ALLOCATION OF RISK BETWEEN THE PARTIES AND ARE AN ESSENTIAL ELEMENT OF THE BASIS OF THE BARGAIN BETWEEN YOU AND SOLARIZER. THE SERVICE WOULD NOT BE PROVIDED WITHOUT THESE LIMITATIONS.
                </p>
              </div>
              <div>
                <h3 className="text-sm font-medium text-foreground mb-2">10.4 Exceptions</h3>
                <p className="text-muted-foreground text-sm leading-relaxed">
                  Nothing in these Terms excludes or limits liability for fraud, gross negligence, willful misconduct, or any liability that cannot be excluded under applicable law.
                </p>
              </div>
            </div>
          </section>

          {/* Section 11: Indemnification */}
          <section id="indemnification">
            <h2 className="text-xl font-semibold text-foreground border-b border-border pb-2 mb-4">
              11. Indemnification
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              You agree to indemnify, defend, and hold harmless Solarizer, its officers, directors, employees, agents, and affiliates from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising out of or related to:
            </p>
            <ol className="text-muted-foreground text-sm space-y-2 ml-6 list-decimal">
              <li>Your use of the Service or any activity under your account.</li>
              <li>Your Content or any allegation that Your Content infringes or misappropriates the intellectual property rights of any third party.</li>
              <li>Your violation of these Terms or any applicable law or regulation.</li>
              <li>Any third-party claim arising from the deployment of smart contracts that were analyzed using the Service, regardless of whether the Service identified or failed to identify any vulnerability.</li>
            </ol>
            <p className="text-muted-foreground leading-relaxed mt-4">
              This indemnification obligation survives termination of your account and these Terms.
            </p>
          </section>

          {/* Section 12: Termination */}
          <section id="termination">
            <h2 className="text-xl font-semibold text-foreground border-b border-border pb-2 mb-4">
              12. Termination
            </h2>
            <div className="space-y-4">
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">12.1 Termination by You</h3>
                <p className="text-muted-foreground leading-relaxed">
                  You may cancel your subscription or delete your account at any time through the dashboard or by contacting{" "}
                  <a href="mailto:hello@solarizer.io" className="text-primary hover:underline">hello@solarizer.io</a>.
                  Upon cancellation, your subscription remains active until the end of the current billing period.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">12.2 Termination by Solarizer</h3>
                <p className="text-muted-foreground leading-relaxed">
                  We may suspend or terminate your account immediately and without notice if: (a) you breach any provision of these Terms; (b) we are required to do so by law or regulation; (c) we reasonably believe your account has been compromised; or (d) we discontinue the Service.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">12.3 Credits upon Termination</h3>
                <ul className="text-muted-foreground text-sm space-y-2 ml-2">
                  <li className="flex items-start gap-2"><span className="text-primary mt-1">•</span><span><strong className="text-foreground">Termination for breach:</strong> All remaining Credits (subscription and purchased) are forfeited immediately.</span></li>
                  <li className="flex items-start gap-2"><span className="text-primary mt-1">•</span><span><strong className="text-foreground">Voluntary cancellation:</strong> Your remaining Credits remain available until the end of your current billing period, after which they expire.</span></li>
                  <li className="flex items-start gap-2"><span className="text-primary mt-1">•</span><span><strong className="text-foreground">Termination by Solarizer (non-breach):</strong> Remaining Credits are applied to any fees owed through the effective date of termination, after which they expire. If the value of remaining Credits exceeds fees owed, we will issue a pro-rated refund for unused purchased Credits bought within the preceding 90 days, where required by applicable law.</span></li>
                </ul>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">12.4 Effect of Termination</h3>
                <p className="text-muted-foreground leading-relaxed">
                  Upon termination: (a) your right to access and use the Service ceases immediately; (b) we may delete your account data in accordance with our Privacy Policy; (c) any Analysis Output stored on the dashboard may be deleted after 30 days. Termination does not affect any rights or obligations that, by their nature, survive termination, including intellectual property rights, disclaimers, limitations of liability, indemnification obligations, and any outstanding payment obligations.
                </p>
              </div>
            </div>
          </section>

          {/* Section 13: Modifications to Terms */}
          <section id="modifications">
            <h2 className="text-xl font-semibold text-foreground border-b border-border pb-2 mb-4">
              13. Modifications to Terms
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              We may update these Terms from time to time. When we make material changes, we will: (a) update the "Last updated" date at the top of these Terms; (b) post a notice on the Service or send notification to the email address associated with your account at least thirty (30) days before the changes take effect.
            </p>
            <p className="text-muted-foreground leading-relaxed mb-4">
              Your continued use of the Service after the effective date of updated Terms constitutes your acceptance of those Terms. If you do not agree with the updated Terms, you must stop using the Service and cancel your subscription before the changes take effect.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              For material changes that substantially alter your rights or obligations, we may require your affirmative consent before the updated Terms apply to your account.
            </p>
          </section>

          {/* Section 14: Governing Law & Dispute Resolution */}
          <section id="governing-law">
            <h2 className="text-xl font-semibold text-foreground border-b border-border pb-2 mb-4">
              14. Governing Law & Dispute Resolution
            </h2>
            <div className="space-y-4">
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">14.1 Governing Law</h3>
                <p className="text-muted-foreground leading-relaxed">
                  These Terms are governed by and construed in accordance with the laws of the Republic of India, without regard to its conflict of laws provisions.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">14.2 Dispute Resolution</h3>
                <p className="text-muted-foreground leading-relaxed">
                  Any dispute, controversy, or claim arising out of or relating to these Terms or the Service shall first be submitted to good-faith negotiation between the parties for a period of thirty (30) days. If the dispute is not resolved through negotiation, it shall be submitted to binding arbitration administered under the rules of the Indian Arbitration and Conciliation Act, 1996, with the seat of arbitration in Bangalore, India.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">14.3 Class Action Waiver</h3>
                <p className="text-muted-foreground leading-relaxed">
                  TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, YOU AGREE THAT ANY DISPUTE RESOLUTION PROCEEDINGS WILL BE CONDUCTED ONLY ON AN INDIVIDUAL BASIS AND NOT IN A CLASS, CONSOLIDATED, OR REPRESENTATIVE ACTION. You waive any right to participate in a class action lawsuit or class-wide arbitration against Solarizer.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">14.4 Small Claims Exception</h3>
                <p className="text-muted-foreground leading-relaxed">
                  Notwithstanding the foregoing, either party may bring an individual action in small claims court for disputes within the court's jurisdictional limits.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">14.5 Injunctive Relief</h3>
                <p className="text-muted-foreground leading-relaxed">
                  Nothing in this section prevents either party from seeking injunctive or other equitable relief in any court of competent jurisdiction to prevent the actual or threatened infringement of intellectual property rights or breach of confidentiality obligations.
                </p>
              </div>
            </div>
          </section>

          {/* Section 15: General Provisions */}
          <section id="general">
            <h2 className="text-xl font-semibold text-foreground border-b border-border pb-2 mb-4">
              15. General Provisions
            </h2>
            <div className="space-y-4">
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">15.1 Severability</h3>
                <p className="text-muted-foreground leading-relaxed">
                  If any provision of these Terms is found to be unenforceable or invalid, that provision shall be modified to the minimum extent necessary to make it enforceable, or if modification is not possible, severed from these Terms. The remaining provisions shall continue in full force and effect.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">15.2 Waiver</h3>
                <p className="text-muted-foreground leading-relaxed">
                  The failure of Solarizer to enforce any right or provision of these Terms shall not constitute a waiver of that right or provision. Any waiver must be in writing and signed by an authorized representative of Solarizer.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">15.3 Entire Agreement</h3>
                <p className="text-muted-foreground leading-relaxed">
                  These Terms, together with the Privacy Policy and any applicable order forms or subscription agreements, constitute the entire agreement between you and Solarizer regarding the Service and supersede all prior agreements, understandings, and communications, whether written or oral.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">15.4 Assignment</h3>
                <p className="text-muted-foreground leading-relaxed">
                  You may not assign or transfer these Terms or any rights or obligations hereunder without our prior written consent. Solarizer may assign these Terms in connection with a merger, acquisition, reorganization, or sale of all or substantially all of its assets, upon notice to you.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">15.5 Force Majeure</h3>
                <p className="text-muted-foreground leading-relaxed">
                  Solarizer shall not be liable for any failure or delay in performance resulting from causes beyond its reasonable control, including but not limited to natural disasters, acts of government, pandemic, war, terrorism, labor disputes, power failures, internet or telecommunications failures, or denial-of-service attacks.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">15.6 Notices</h3>
                <p className="text-muted-foreground leading-relaxed">
                  Notices to you may be provided via the email address associated with your account or through the Service. Notices to Solarizer must be sent to{" "}
                  <a href="mailto:hello@solarizer.io" className="text-primary hover:underline">hello@solarizer.io</a>.
                  Notices are deemed received upon delivery (for email) or upon posting (for in-Service notifications).
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">15.7 Headings</h3>
                <p className="text-muted-foreground leading-relaxed">
                  Section headings are for convenience only and do not affect the interpretation of these Terms.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-foreground mb-2">15.8 Third-Party Beneficiaries</h3>
                <p className="text-muted-foreground leading-relaxed">
                  These Terms do not create any third-party beneficiary rights.
                </p>
              </div>
            </div>
          </section>

          {/* Section 16: Contact */}
          <section id="contact">
            <h2 className="text-xl font-semibold text-foreground border-b border-border pb-2 mb-4">
              16. Contact
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              For questions about these Terms, contact:
            </p>
            <div className="bg-muted/30 border border-border rounded-lg p-4">
              <p className="text-foreground font-medium">Solarizer</p>
              <p className="text-muted-foreground text-sm">
                Email:{" "}
                <a href="mailto:hello@solarizer.io" className="text-primary hover:underline">hello@solarizer.io</a>
              </p>
            </div>
          </section>
        </div>

        {/* Footer Links */}
        <div className="mt-12 pt-8 border-t border-border">
          <p className="text-muted-foreground text-sm">
            See also our{" "}
            <Link to="/privacy" className="text-primary hover:underline">
              Privacy Policy
            </Link>
            .
          </p>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default TermsOfService;
